<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="88927" started-at="2021-08-27T13:17:13Z" finished-at="2021-08-27T13:18:41Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="88927" started-at="2021-08-27T13:17:13Z" finished-at="2021-08-27T13:18:41Z">
      <class name="com.vtiger.airtel.CreateOrganizationWithIndustryTypeTest">
        <test-method status="PASS" signature="configBS()[pri:0, instance:com.vtiger.airtel.CreateOrganizationWithIndustryTypeTest@59f99ea]" name="configBS" is-config="true" duration-ms="16" started-at="2021-08-27T18:47:13Z" finished-at="2021-08-27T18:47:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBS -->
        <test-method status="PASS" signature="configBC()[pri:0, instance:com.vtiger.airtel.CreateOrganizationWithIndustryTypeTest@59f99ea]" name="configBC" is-config="true" duration-ms="33983" started-at="2021-08-27T18:47:13Z" finished-at="2021-08-27T18:47:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBC -->
        <test-method status="PASS" signature="configBM()[pri:0, instance:com.vtiger.airtel.CreateOrganizationWithIndustryTypeTest@59f99ea]" name="configBM" is-config="true" duration-ms="24373" started-at="2021-08-27T18:47:47Z" finished-at="2021-08-27T18:48:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method status="FAIL" signature="createOrganizationWithIndustryTypeTest()[pri:0, instance:com.vtiger.airtel.CreateOrganizationWithIndustryTypeTest@59f99ea]" name="createOrganizationWithIndustryTypeTest" duration-ms="290" started-at="2021-08-27T18:48:11Z" finished-at="2021-08-27T18:48:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.vtiger.airtel.CreateOrganizationWithIndustryTypeTest.createOrganizationWithIndustryTypeTest(CreateOrganizationWithIndustryTypeTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createOrganizationWithIndustryTypeTest -->
        <test-method status="PASS" signature="configAM()[pri:0, instance:com.vtiger.airtel.CreateOrganizationWithIndustryTypeTest@59f99ea]" name="configAM" is-config="true" duration-ms="24918" started-at="2021-08-27T18:48:15Z" finished-at="2021-08-27T18:48:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method status="PASS" signature="configAC()[pri:0, instance:com.vtiger.airtel.CreateOrganizationWithIndustryTypeTest@59f99ea]" name="configAC" is-config="true" duration-ms="1497" started-at="2021-08-27T18:48:40Z" finished-at="2021-08-27T18:48:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAC -->
        <test-method status="PASS" signature="configAS()[pri:0, instance:com.vtiger.airtel.CreateOrganizationWithIndustryTypeTest@59f99ea]" name="configAS" is-config="true" duration-ms="0" started-at="2021-08-27T18:48:42Z" finished-at="2021-08-27T18:48:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAS -->
      </class> <!-- com.vtiger.airtel.CreateOrganizationWithIndustryTypeTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
